FROM python:3.11-slim

WORKDIR /app

COPY ui.py .
COPY requirements.ui.txt .

RUN pip install --no-cache-dir -r requirements.ui.txt

CMD ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]